const CHARACTERS = [
  {
    id: 'pawnie',
    name: 'Pawnie',
    title: 'The Village Rookie',
    level: 1,
    dialogue: {
      before: "H-hi there! I'm Pawnie, and this is my very first real battle! The elder pawns told me to always move forward, never look back. I hope I don't mess this up too badly... Please be gentle with me!",
      after: "Wow... you really are strong! I gave it my best shot, but I still have so much to learn. Maybe one day I'll make it to the other side and become a queen too! Thanks for the lesson!",
      win: "I-I won?! I actually won! Wait until the other pawns hear about this! The littlest piece on the board just beat a real challenger! This is the happiest day of my life!",
    },
    personality: 'nervous',
    colors: { primary: '#88ccff', secondary: '#4488cc', skin: '#ffcc99', eye: '#ffffff', pupil: '#224466' },
  },
  {
    id: 'bishbosh',
    name: 'Bish-Bosh',
    title: 'The Diagonal Dreamer',
    level: 2,
    dialogue: {
      before: "Heh heh heh... welcome to my domain of diagonals! You think you can handle the slash and the slash-back? I have been training on the light squares my entire life. Prepare yourself!",
      after: "Impressive... you navigated my diagonals better than I expected. Most challengers get lost in the cross-pattern. You have a sharp eye. Perhaps the straight paths are not so boring after all.",
      win: "Ha! Did you see that fork? That pin? My bishop pair controlled the whole board! The diagonal is the true path to victory, my friend. Come back when you understand the power of the slash!",
    },
    personality: 'enthusiastic',
    colors: { primary: '#ff9966', secondary: '#cc6633', skin: '#ffcc99', eye: '#ffffff', pupil: '#663322' },
  },
  {
    id: 'rokee',
    name: 'Rook-E',
    title: 'The Iron Tower',
    level: 3,
    dialogue: {
      before: "Straight lines. No shortcuts. No fancy diagonal tricks. That is how we do things on the rank and file. I have stood guard on this corner for a thousand games. Show me if you have the discipline to break through.",
      after: "Solid play. You respected the fundamentals and outmaneuvered my fortress. A tower can be toppled by patience and precision. You have both. I salute your technique.",
      win: "As I said: straight lines win games. You tried to dance around the board, but you cannot outrun the iron tower. When the seventh rank opens, it is already too late. Better luck next time.",
    },
    personality: 'stoic',
    colors: { primary: '#aabbcc', secondary: '#667788', skin: '#ddbb99', eye: '#ffffff', pupil: '#334455' },
  },
  {
    id: 'knightsade',
    name: 'KnightShade',
    title: 'The Shadow Lancer',
    level: 4,
    dialogue: {
      before: "*silence* ... You cannot see me coming. No piece on this board moves like I do. I leap over walls, strike from behind, and vanish before you know what happened. Do not bother predicting me.",
      after: "*low whistle* ... You actually saw through my shadows. That knight fork you avoided in the middlegame? Nobody avoids that. You are not like the others. I respect that. Until we meet again.",
      win: "*chuckle* ... Did you feel that? The moment your queen was forked and your king was exposed? That is the sound of the shadows claiming another victim. The Lancer always strikes true.",
    },
    personality: 'mysterious',
    colors: { primary: '#6644aa', secondary: '#442288', skin: '#ccbbdd', eye: '#ffcc00', pupil: '#221144' },
  },
  {
    id: 'queenie',
    name: 'Queenie',
    title: 'The Royal Tyrant',
    level: 5,
    dialogue: {
      before: "Oh my, another challenger? How adorable. Do you know who I am? I am the most powerful piece on this board, darling. I move in every direction, any distance. Bow before your queen!",
      after: "Not bad! Not bad at all! You actually managed to outplay me! I have not been defeated in fifty games. You have earned a curtsy from the queen herself. Consider this an honor!",
      win: "Did you really think you could defeat the queen? I am the sun around which this board revolves. Every piece bows to my movement. Off with your king! That is how the monarchy works, darling.",
    },
    personality: 'dramatic',
    colors: { primary: '#ff66aa', secondary: '#cc4488', skin: '#ffddcc', eye: '#ffffff', pupil: '#661144' },
  },
  {
    id: 'castle',
    name: 'CastlE',
    title: 'The Unbreakable Fortress',
    level: 6,
    dialogue: {
      before: "I am the wall. I am the shield. I am the fortress that has never fallen. You can throw your strongest pieces at me, but they will break against my defenses. Patience is my weapon. Come, test the wall.",
      after: "The wall has fallen. You breached my defenses with a patience that matched my own. I have not seen such methodical dismantling in centuries. You are a true siege master. Well fought.",
      win: "The fortress stands. Your attacks were predictable, your sacrifices wasteful. A true defender knows that the best offense is a perfect defense. My pawns are your tombstones. Impenetrable!",
    },
    personality: 'patient',
    colors: { primary: '#88aa88', secondary: '#557755', skin: '#ccbb99', eye: '#ffffff', pupil: '#224422' },
  },
  {
    id: 'endgamer',
    name: 'EndGamer',
    title: 'The Patient Scholar',
    level: 7,
    dialogue: {
      before: "The opening is merely a handshake. The middlegame is just conversation. The TRUE battle happens in the endgame, when only a handful of pieces remain. I have studied every endgame position known to chess. I will see you there.",
      after: "You outplayed me in the endgame. That is not supposed to happen. I have memorized Lucena, Philidor, and the Vancura. Yet you found a path I did not see. You are a scholar as well as a warrior.",
      win: "As I predicted. You played aggressively in the opening, burned your advantages in the middlegame, and arrived at the endgame with nothing. The endgame is where preparation meets opportunity. I had both.",
    },
    personality: 'calm',
    colors: { primary: '#5599cc', secondary: '#3377aa', skin: '#ccddcc', eye: '#ffffff', pupil: '#113355' },
  },
  {
    id: 'forkmaster',
    name: 'ForkMaster',
    title: 'The Tactician',
    level: 8,
    dialogue: {
      before: "Can you spot the fork? I can. I see three of them right now, and we have not even started. Tactics flow like water through my mind. Every piece you place is a target. Every move you make is a mistake waiting to happen.",
      after: "You avoided my forks. You sidestepped my pins. You escaped my skewers. That is rare. Most opponents are tactical roadkill by move fifteen. You must have trained specifically for me. I am impressed.",
      win: "Forked again! Your queen and rook were lined up like dominoes. Did you not see it coming? Tactics, my friend. Tactics win games. You can have all the strategy in the world, but one fork ends it all.",
    },
    personality: 'smug',
    colors: { primary: '#dd8844', secondary: '#bb6622', skin: '#ffcc99', eye: '#ffffff', pupil: '#553311' },
  },
  {
    id: 'checkmate',
    name: 'Checkmate',
    title: 'The Executioner',
    level: 9,
    dialogue: {
      before: "Every move brings you closer to your end. I do not play chess. I orchestrate checkmates. Your king is already marked. The only question is how many moves until the final blow. Let us begin the countdown.",
      after: "You... you dodged my traps. You survived the mating net. You found resources where there should have been none. I have executed a thousand kings, but you... you are different. The Executioner bows to you.",
      win: "Check. And mate. As foreseen. Your king is surrounded, your army scattered, your hopes crushed. There was never any doubt. The Executioner does not miss. Your soul belongs to the board now.",
    },
    personality: 'ominous',
    colors: { primary: '#882222', secondary: '#551111', skin: '#ddbbbb', eye: '#ff4444', pupil: '#220000' },
  },
  {
    id: 'grandmasterx',
    name: 'Grandmaster X',
    title: 'The Absolute',
    level: 10,
    dialogue: {
      before: "You have climbed the mountain. You have defeated nine challengers. But reaching the summit and conquering it are different things entirely. I am not merely a chess player. I am chess itself. Make your first move. It will also be your last.",
      after: "Impossible... IMPOSSIBLE! I have not lost a game in thirty years. I have faced grandmasters, computers, and champions. Yet you... you found the truth within the lies. Chess 2.0 is yours. The throne is empty. Take it.",
      win: "You were strong. Stronger than the others. But strength without perfection is merely potential. And potential, my friend, is wasted on the dead. I am the Absolute. I was before chess, and I will be after. Rest now.",
    },
    personality: 'serious',
    colors: { primary: '#ffcc00', secondary: '#cc9900', skin: '#ffdd99', eye: '#ff6600', pupil: '#332200' },
  },
];
