// Lore for the stops on each world's place map (src/screens/WorldMissionsScreen.js),
// in trail order, one per stop: { place, text }. Shown on the stop's info panel and
// on a parchment card the first time the stop is played.
const PLACE_LORE = {
  pawnhollow: [
    { place: 'The Village Green', text: 'Pawn Hollow\'s stone board, where every pawn learns to play. Three nights ago a light fell behind the windmill, and since then no new crack has opened anywhere.' },
  ],
  trainingcamp: [
    { place: 'The Drill Yard', text: 'Ten stone boards in two straight rows. Sergeant Square drills every recruit here until they can finish a king in one move, eyes closed.' },
    { place: 'The Endgame Ring', text: 'A ring of sand where you always start ahead. The Captain\'s crew makes you prove you can finish the job. Being ahead is only half of winning.' },
    { place: 'The Arcade Hall', text: 'Eighteen lamps, one for every challenge a capture can start. Joy Stick lights them one by one as you learn each game. Nobody has found the off switch.' },
    { place: 'The Hall of Rules', text: 'Every twist the guardians use is written here, in a book nobody has finished. The mist never lifts, and one piece inside is never what it seems.' },
    { place: 'Sensei\'s Dojo', text: 'The oldest hall on the mountain. Sensei Tactic says he taught one other student who learned this fast. He will not say who, or when.' },
  ],
  slantedsands: [
    { place: 'The Mirage Pool', text: 'Travellers see cool water here and walk for hours toward it. Mirage hides three mates in the shimmer. Look twice before you drink, or move.' },
    { place: 'The Scarab Burrows', text: 'The scarabs dig all day and bury everything they find. Somewhere in the swarm, one of them carries the Sun Scarab, the oldest treasure of the Sands.' },
    { place: 'The Great Dune', text: 'The tallest dune in the desert, and it moves a little every night. The Sand Sprite races anyone who climbs it, and has never lost on home ground.' },
    { place: 'The Tilted Court', text: 'Bish-Bosh built this court on the diagonal so his apprentice would never learn straight lines. Only bishops play here. Bishling thinks that is fair.' },
    { place: 'The Pawn Track', text: 'Four lanes raked in the sand, one finish line. The Dust Devil swears a lone pawn once raced here at night, faster than anyone, straight toward the edge.' },
    { place: 'The Sunstone Field', text: 'The sunstones kept the desert warm at night, until the rifts buried them. Sidewinder guards them now. Dig them up and the dunes remember the sun.' },
    { place: 'The Night Sand', text: 'Here the sand stays cool and dark, even at noon. Footprints glow in it, walking toward the far edge. They are your size. They are yours.' },
    { place: 'The Leaning Pyramid', text: 'Bish-Bosh tilted his pyramid to point where he wants to go. Inside he keeps the Tilted Compass. Since the night the sky cracked, it has pointed only at you.' },
  ],
  ironkeep: [
    { place: 'The Outer Forge', text: 'Every bar of iron in the Keep was hammered here. Anvil tests all who come to the gate with three trials in the heat. Tempered steel passes.' },
    { place: 'The West Gate', text: 'An old ram waits under its shed, aimed at a gate it never broke. Portcullis says one straight line opens any door. Find the rook move that does.' },
    { place: 'The Sentry Line', text: 'Four rook towers watch the road day and night. One of them holds the gate key. They went up after the crossing, so no piece could slip past again.' },
    { place: 'The Empty Plinths', text: 'Four towers stood here once. Rook-E moved them to the walls and left the plinths bare. His squire Rivet wants to see how you fight without them.' },
    { place: 'The East Gate', text: 'The Siege Captain has camped outside this gate longer than anyone remembers. Every gate falls, he says. Hold it with one rook for twelve moves.' },
    { place: 'The Ingot Yard', text: 'Hot ingots spill from the carts on their way to the walls, and Bellows keeps them glowing. Carry them off before they cool, or before he catches you.' },
    { place: 'The Inner Gate', text: 'On the night of the crossing this gate stood open for you. Then a sealed message came, and it began to close. A ghost of that light still waits in it.' },
    { place: 'Rook-E\'s Keep', text: 'The great keep, riveted shut. Rook-E guards its gate and the Iron Key to the road north. His orders came sealed, long ago. He never says from whom.' },
  ],
  mistymoors: [
    { place: 'The Fogbank', text: 'Fog pools in this hollow like milk in a bowl. Wisp hides one true light among many false ones, and only sharp eyes pick the right one.' },
    { place: 'The Old Watchtower', text: 'The tower\'s lantern has burned for a hundred years, and no one knows who fills it. Crow watches from the top and asks riddles only a knight can answer.' },
    { place: 'The Wisp Marsh', text: 'Lights dance over the black pools to lure walkers off the boardwalk. The Bog Lantern has swallowed many a boot. Keep up, and keep your footing.' },
    { place: 'The Riders\' Ring', text: 'Four phantom knights gallop round these standing stones every night. They guarded the Moors once, and they still ride as if the board were whole.' },
    { place: 'The Barrow', text: 'An old burial mound where the fog lies thickest. The Barrow Wight waits inside with cold hands, sure that nobody ever finds the way out of his mist.' },
    { place: 'The Four Lanterns', text: 'Glimmer blew out these four lanterns and forgot where it hid their light. Light them all again, and the fog on the road ahead will thin.' },
    { place: 'The Lost Footprints', text: 'Glowing footprints cross the heather, then stop. Someone walked here in the dark with a lantern, whispering: just a few more ranks. It was you.' },
    { place: 'The Knight\'s Crag', text: 'A cliff shaped like a horse\'s head. From here the Knight of the Mist saw the night the board broke. He keeps the Mist Lantern, which shows what others hide.' },
  ],
  royalpalace: [
    { place: 'The Tournament Grounds', text: 'Queenie built this arena for The Queen\'s Cup: sixteen players, four groups, then knockout. She receives nobody, except the one who wins her Cup.' },
    { place: 'The Queen\'s Balcony', text: 'Grandmaster X gave Queenie this palace to keep a secret about your crossing. She fans herself up here, stamps every order with her Signet, and hates to lose.' },
  ],
  clockworkcitadel: [
    { place: 'The Gear Maze', text: 'Cog built these walls to send visitors round in circles. Somewhere inside, one of his pieces carries the winding key that keeps the maze turning.' },
    { place: 'The Tower Clock', text: 'The oldest clock in the Citadel. Chime rings the hours from its belfry. The bell rang once more the night the sky cracked, then fell silent for years.' },
    { place: 'The Mainspring', text: 'The heart of the Citadel: one great spring that drives every gear. Mainspring asks to be wound with care. Too hard, and the whole city jumps.' },
    { place: 'The Parade Deck', text: 'Tin soldiers march here all day, wound up for battle. Their springs run for twenty-five moves and not one more, so round them up quickly.' },
    { place: 'The Engine Rails', text: 'The Engine rolls up and down its rails, puffing steam and jamming squares. CastlE built it to break sieges. Today it is rolling at you.' },
    { place: 'The Loose Cogs', text: 'Four cogs shook loose from the great clock and lie scattered on the deck. Sprocket, the spare part, begs you to set them back before the city winds down.' },
    { place: 'The Stopped Clocks', text: 'Every clock in this square stopped at the same second: the second the Great Board broke. None has moved since. You remember the sudden silence.' },
    { place: 'CastlE\'s Keep', text: 'Four gear walls ring the keep, built for one piece only: you. CastlE, Rook-E\'s brother, keeps the Broken Seal of the orders to stop anyone crossing.' },
  ],
  grandlibrary: [
    { place: 'The Front Desk', text: 'The Librarian hushes every visitor at the door. Slips of paper flutter off her desk: three quiet mates, scribbled in the margins of old games.' },
    { place: 'The Back Rank Wing', text: 'Every book in this wing ends on the last row. The Archivist, the EndGamer\'s assistant, files them by the rook move that finishes each one.' },
    { place: 'The Knight\'s Alcove', text: 'Inkwell tipped over here long ago, and the ink never dried. In this alcove, kings hide behind their own pieces, until a knight jumps in.' },
    { place: 'The Queen\'s Reading Room', text: 'Madam Folio keeps the fire lit and the silence strict. Her marble queen watches the armchairs: a queen may go anywhere, which makes her hard to aim.' },
    { place: 'The Closed Stacks', text: 'The Night Porter locks these shelves at dusk. The books behind the bars are full of checks, but in each one only a single move is mate.' },
    { place: 'The Great Lectern', text: 'A giant book turns its own pages here, looking for its last chapter. Bookend holds that page, and gives it only to a pawn that reaches the far edge.' },
    { place: 'The Writing Desk', text: 'A blank book waits here with a pen that fits your hand. You sat at this desk once, before the crossing, and wrote the first letter of your name.' },
    { place: 'The Great Reading Room', text: 'Under the glass dome, the EndGamer reads a book about you. He took the Map of the Crossing before the Grandmaster could burn it, and guards a fragment too.' },
  ],
  forkedgulch: [
    { place: 'Shootout Plaza', text: 'Sixteen guns ride into the Gulch for the Shootout. The bracket board is covered in wanted posters, and yours is nailed at the very top. Biggest bounty in town.' },
    { place: 'Two Prongs Saloon', text: 'ForkMaster built his saloon where the canyon splits in two. He was paid to hunt you, and the poster he carries is signed at the bottom. Win it, and you will know by whom.' },
  ],
  obsidiancourt: [
    { place: 'Bailiff\'s Gate', text: 'Every trial starts at this gate. The Bailiff turns his little hourglass the moment you step through. Twenty-five moves, and the sand is already falling.' },
    { place: 'The Judge\'s Bench', text: 'Three stone tablets stand before the Judge. Each holds a case that ends with one quiet queen move. The verdicts glow when they are delivered.' },
    { place: 'The Fire Pool', text: 'The floor of the Court is lava, and Magma likes it that way. Stepping stones cross the pool to a rock island, where the trials are held.' },
    { place: 'The Jury Box', text: 'Twelve grim stone faces sit in the box. They have found every piece guilty since the Court was built. Dismiss them all before the sand runs out.' },
    { place: 'The Headsman\'s Block', text: 'The Executioner\'s Axe waits at the block, sharp and patient. Appeals are heard here, with no queen and no rooks at your side. Few are granted.' },
    { place: 'The Four Braziers', text: 'The braziers keep the embers of old verdicts burning. Cinder scatters them over the board for anyone brave enough to gather them. Be quick.' },
    { place: 'The Brink', text: 'From this ledge you can see across the lava to where a crystal king once stood and watched you. He turned an hourglass over and whispered: not this one.' },
    { place: 'Court of Judgement', text: 'Checkmate guards the last road for Grandmaster X. His hourglass has never stopped for anyone. He holds a fragment of the Great Board, and he means to finish what the breaking began.' },
  ],
  soulboundpixel: [
    { place: 'Hall of Echoes', text: 'Echo is what Grandmaster X remembers of every game he played alone. Three ghost kings replay them over and over. He never solved them.' },
    { place: 'Shardling\'s Toll', text: 'Past the crystal gate, every capture has a price. The Shardling counts shard coins and lets you through only when your debts are paid.' },
    { place: 'The Mirror', text: 'Mirror shows you only your worst: the challenges you lose most. Look into the glass, win three of five, and walk on.' },
    { place: 'The Prism', text: 'Prism bends the light into fog and rainbows. Somewhere in the haze is its true face. Find it, and the fragment clears.' },
    { place: 'The Last Rank', text: 'The Edge remembers the pawns that reached the last row. A crown hangs over it, waiting. Bring one of yours home and it shines again.' },
    { place: 'Shard Storm', text: 'Five shards of the Great Board still spin here in the void. They are warm when you touch them, as if they know you.' },
    { place: 'One Square Away', text: 'Here is where you stood on the night of the crossing, one square from the edge. Then the board cracked like ice and everything went white.' },
    { place: 'The Board\'s Far Edge', text: 'Grandmaster X waits at the far edge of what is left of the Great Board. He broke it world by world so no one could cross. You are the one who almost did.' },
  ],
};
