// Generated by scripts/generate_backgrounds.py; edit that script, not this file.
// Layer positions and sizes are in 640x400 art pixels (one = two game units).
const BACKGROUND_SCENES = {
 "clockworkcitadel": {
  "layers": [
   {
    "file": "clockworkcitadel_clouds.png",
    "h": 197,
    "motion": {
     "speed": 4,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 32
   },
   {
    "file": "clockworkcitadel_airship0.png",
    "h": 43,
    "motion": {
     "amp": 3,
     "period": 6,
     "speed": -5,
     "type": "bob"
    },
    "w": 110,
    "x": 359,
    "y": 44
   },
   {
    "file": "clockworkcitadel_city.png",
    "h": 311,
    "motion": {
     "type": "static"
    },
    "w": 635,
    "x": 4,
    "y": 89
   },
   {
    "file": "clockworkcitadel_windows.png",
    "h": 220,
    "motion": {
     "max": 1.0,
     "min": 0.5,
     "speed": 2,
     "type": "flicker"
    },
    "w": 616,
    "x": 13,
    "y": 180
   },
   {
    "file": "clockworkcitadel_smoke.png",
    "h": 119,
    "motion": {
     "amount": 0.05,
     "period": 6,
     "pivot": [
      235,
      224
     ],
     "type": "sway"
    },
    "w": 555,
    "x": 85,
    "y": 76
   },
   {
    "file": "clockworkcitadel_hour8.png",
    "h": 16,
    "motion": {
     "center": [
      2,
      11
     ],
     "speed": 0.03,
     "type": "spin"
    },
    "w": 5,
    "x": 34,
    "y": 165
   },
   {
    "file": "clockworkcitadel_minute8.png",
    "h": 22,
    "motion": {
     "center": [
      2,
      17
     ],
     "speed": 0.35,
     "type": "spin"
    },
    "w": 5,
    "x": 34,
    "y": 159
   },
   {
    "file": "clockworkcitadel_hour522.png",
    "h": 18,
    "motion": {
     "center": [
      2,
      13
     ],
     "speed": 0.03,
     "type": "spin"
    },
    "w": 5,
    "x": 551,
    "y": 143
   },
   {
    "file": "clockworkcitadel_minute522.png",
    "h": 25,
    "motion": {
     "center": [
      2,
      20
     ],
     "speed": 0.35,
     "type": "spin"
    },
    "w": 5,
    "x": 551,
    "y": 136
   },
   {
    "file": "clockworkcitadel_gear0.png",
    "h": 70,
    "motion": {
     "center": [
      36,
      35
     ],
     "speed": 0.25,
     "type": "spin"
    },
    "w": 72,
    "x": 144,
    "y": 295
   },
   {
    "file": "clockworkcitadel_gear1.png",
    "h": 52,
    "motion": {
     "center": [
      26,
      26
     ],
     "speed": -0.34,
     "type": "spin"
    },
    "w": 52,
    "x": 189,
    "y": 342
   },
   {
    "file": "clockworkcitadel_gear2.png",
    "h": 82,
    "motion": {
     "center": [
      41,
      41
     ],
     "speed": -0.2,
     "type": "spin"
    },
    "w": 82,
    "x": 419,
    "y": 289
   }
  ]
 },
 "crystal": {
  "effects": [
   {
    "amp": [
     2,
     5
    ],
    "cell": 10,
    "rect": [
     0,
     0.3,
     0.14,
     0.7
    ],
    "speed": [
     0,
     -30
    ],
    "type": "ripple"
   },
   {
    "amp": [
     2,
     5
    ],
    "cell": 10,
    "rect": [
     0.86,
     0.3,
     1,
     0.7
    ],
    "speed": [
     0,
     -30
    ],
    "type": "ripple"
   }
  ]
 },
 "forkedgulch": {
  "effects": [
   {
    "rect": [
     0,
     0,
     1,
     0.45
    ],
    "speed": 5,
    "type": "skyDrift"
   },
   {
    "amp": [
     1,
     2
    ],
    "cell": 20,
    "rect": [
     0,
     0.52,
     1,
     0.66
    ],
    "speed": [
     0,
     8
    ],
    "type": "ripple"
   },
   {
    "amp": [
     3,
     1
    ],
    "cell": 70,
    "rect": [
     0,
     0.64,
     0.52,
     1
    ],
    "speed": [
     8,
     0
    ],
    "type": "ripple"
   },
   {
    "amp": [
     3,
     1
    ],
    "cell": 70,
    "rect": [
     0.82,
     0.64,
     1,
     0.8
    ],
    "speed": [
     8,
     0
    ],
    "type": "ripple"
   }
  ]
 },
 "grandlibrary": {
  "layers": [
   {
    "file": "grandlibrary_moonlight.png",
    "h": 136,
    "motion": {
     "max": 0.7,
     "min": 0.35,
     "period": 9,
     "type": "pulse"
    },
    "w": 261,
    "x": 189,
    "y": 262
   },
   {
    "file": "grandlibrary_candle0.png",
    "h": 19,
    "motion": {
     "amp": 4,
     "period": 4.0,
     "phase": 0,
     "speed": 0,
     "type": "bob"
    },
    "w": 9,
    "x": 186,
    "y": 34
   },
   {
    "file": "grandlibrary_candle1.png",
    "h": 19,
    "motion": {
     "amp": 4,
     "period": 4.7,
     "phase": 1,
     "speed": 0,
     "type": "bob"
    },
    "w": 9,
    "x": 436,
    "y": 44
   },
   {
    "file": "grandlibrary_candle2.png",
    "h": 19,
    "motion": {
     "amp": 4,
     "period": 5.4,
     "phase": 2,
     "speed": 0,
     "type": "bob"
    },
    "w": 9,
    "x": 226,
    "y": 14
   },
   {
    "file": "grandlibrary_candle3.png",
    "h": 19,
    "motion": {
     "amp": 4,
     "period": 6.1,
     "phase": 3,
     "speed": 0,
     "type": "bob"
    },
    "w": 9,
    "x": 406,
    "y": 12
   },
   {
    "file": "grandlibrary_book0.png",
    "h": 8,
    "motion": {
     "amp": 5,
     "period": 5,
     "phase": 0,
     "speed": 0,
     "type": "bob"
    },
    "w": 21,
    "x": 200,
    "y": 89
   },
   {
    "file": "grandlibrary_book1.png",
    "h": 8,
    "motion": {
     "amp": 5,
     "period": 6,
     "phase": 2,
     "speed": 0,
     "type": "bob"
    },
    "w": 21,
    "x": 420,
    "y": 109
   },
   {
    "file": "grandlibrary_lamps.png",
    "h": 157,
    "motion": {
     "max": 1.0,
     "min": 0.5,
     "speed": 3,
     "type": "flicker"
    },
    "w": 497,
    "x": 72,
    "y": 140
   }
  ]
 },
 "ironkeep": {
  "layers": [
   {
    "file": "ironkeep_clouds.png",
    "h": 147,
    "motion": {
     "speed": 3,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 42
   },
   {
    "file": "ironkeep_forge.png",
    "h": 147,
    "motion": {
     "max": 1.0,
     "min": 0.4,
     "period": 2.2,
     "type": "pulse"
    },
    "w": 49,
    "x": 68,
    "y": 234
   },
   {
    "file": "ironkeep_portcullis.png",
    "h": 111,
    "motion": {
     "type": "static"
    },
    "w": 45,
    "x": 70,
    "y": 232
   },
   {
    "file": "ironkeep_windows.png",
    "h": 77,
    "motion": {
     "max": 1.0,
     "min": 0.5,
     "speed": 3,
     "type": "flicker"
    },
    "w": 584,
    "x": 26,
    "y": 180
   },
   {
    "file": "ironkeep_flags.png",
    "h": 38,
    "motion": {
     "amount": 0.02,
     "period": 2.4,
     "pivot": [
      580,
      10
     ],
     "type": "sway"
    },
    "w": 595,
    "x": 30,
    "y": 100
   },
   {
    "file": "ironkeep_smoke.png",
    "h": 92,
    "motion": {
     "amount": 0.05,
     "period": 7,
     "pivot": [
      3,
      145
     ],
     "type": "sway"
    },
    "w": 51,
    "x": 537,
    "y": 75
   }
  ]
 },
 "mistymoors": {
  "layers": [
   {
    "file": "mistymoors_fog_high.png",
    "h": 133,
    "motion": {
     "speed": 2.5,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 64
   },
   {
    "file": "mistymoors_lantern.png",
    "h": 9,
    "motion": {
     "max": 1.0,
     "min": 0.2,
     "speed": 2,
     "type": "flicker"
    },
    "w": 9,
    "x": 570,
    "y": 221
   },
   {
    "file": "mistymoors_fog_mid.png",
    "h": 95,
    "motion": {
     "speed": -4,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 222
   },
   {
    "file": "mistymoors_tree0.png",
    "h": 79,
    "motion": {
     "amount": 0.015,
     "period": 5,
     "pivot": [
      42,
      78
     ],
     "type": "sway"
    },
    "w": 57,
    "x": 58,
    "y": 282
   },
   {
    "file": "mistymoors_tree1.png",
    "h": 90,
    "motion": {
     "amount": 0.015,
     "period": 6,
     "pivot": [
      43,
      89
     ],
     "type": "sway"
    },
    "w": 77,
    "x": 557,
    "y": 279
   },
   {
    "file": "mistymoors_crow0.png",
    "h": 6,
    "motion": {
     "amp": 3,
     "period": 0.9,
     "phase": 0,
     "speed": -6,
     "type": "fly"
    },
    "w": 15,
    "x": 243,
    "y": 108
   },
   {
    "file": "mistymoors_crow1.png",
    "h": 6,
    "motion": {
     "amp": 3,
     "period": 0.9,
     "phase": 1,
     "speed": -9,
     "type": "fly"
    },
    "w": 15,
    "x": 293,
    "y": 128
   },
   {
    "file": "mistymoors_fog_low.png",
    "h": 77,
    "motion": {
     "speed": 6,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 322
   }
  ]
 },
 "obsidiancourt": {
  "layers": [
   {
    "file": "obsidiancourt_smoke.png",
    "h": 167,
    "motion": {
     "speed": 3,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 2
   },
   {
    "file": "obsidiancourt_braziers.png",
    "h": 29,
    "motion": {
     "max": 1.0,
     "min": 0.5,
     "speed": 4,
     "type": "flicker"
    },
    "w": 349,
    "x": 146,
    "y": 244
   },
   {
    "file": "obsidiancourt_lava.png",
    "h": 25,
    "motion": {
     "max": 0.9,
     "min": 0.3,
     "period": 3,
     "type": "pulse"
    },
    "w": 625,
    "x": 8,
    "y": 368
   },
   {
    "file": "obsidiancourt_lava_flow.png",
    "h": 35,
    "motion": {
     "speed": 10,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 364
   }
  ]
 },
 "pawnhollow": {
  "layers": [
   {
    "file": "pawnhollow_clouds.png",
    "h": 127,
    "motion": {
     "speed": 4,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 22
   },
   {
    "file": "pawnhollow_bird0.png",
    "h": 3,
    "motion": {
     "amp": 3,
     "period": 0.7,
     "phase": 0,
     "speed": 9,
     "type": "fly"
    },
    "w": 9,
    "x": 236,
    "y": 68
   },
   {
    "file": "pawnhollow_bird1.png",
    "h": 3,
    "motion": {
     "amp": 3,
     "period": 0.8999999999999999,
     "phase": 1,
     "speed": 7,
     "type": "fly"
    },
    "w": 9,
    "x": 276,
    "y": 88
   },
   {
    "file": "pawnhollow_sails.png",
    "h": 88,
    "motion": {
     "center": [
      44,
      44
     ],
     "speed": 0.5,
     "type": "spin"
    },
    "w": 88,
    "x": 26,
    "y": 150
   },
   {
    "file": "pawnhollow_smoke.png",
    "h": 64,
    "motion": {
     "amount": 0.05,
     "period": 6,
     "pivot": [
      3,
      58
     ],
     "type": "sway"
    },
    "w": 511,
    "x": 129,
    "y": 209
   },
   {
    "file": "pawnhollow_tree0.png",
    "h": 72,
    "motion": {
     "amount": 0.018,
     "period": 4.5,
     "phase": 0.0,
     "pivot": [
      22,
      72
     ],
     "type": "sway"
    },
    "w": 61,
    "x": 0,
    "y": 328
   },
   {
    "file": "pawnhollow_tree1.png",
    "h": 56,
    "motion": {
     "amount": 0.018,
     "period": 5.1,
     "phase": 1.1,
     "pivot": [
      29,
      56
     ],
     "type": "sway"
    },
    "w": 60,
    "x": 111,
    "y": 344
   },
   {
    "file": "pawnhollow_tree2.png",
    "h": 50,
    "motion": {
     "amount": 0.018,
     "period": 5.7,
     "phase": 2.2,
     "pivot": [
      26,
      50
     ],
     "type": "sway"
    },
    "w": 53,
    "x": 444,
    "y": 350
   },
   {
    "file": "pawnhollow_tree3.png",
    "h": 78,
    "motion": {
     "amount": 0.018,
     "period": 6.3,
     "phase": 3.3000000000000003,
     "pivot": [
      40,
      78
     ],
     "type": "sway"
    },
    "w": 70,
    "x": 570,
    "y": 322
   }
  ]
 },
 "royalpalace": {
  "layers": [
   {
    "file": "royalpalace_light.png",
    "h": 148,
    "motion": {
     "max": 0.9,
     "min": 0.4,
     "period": 7,
     "type": "pulse"
    },
    "w": 266,
    "x": 187,
    "y": 250
   },
   {
    "file": "royalpalace_curtain0.png",
    "h": 270,
    "motion": {
     "amount": 0.01,
     "period": 6,
     "pivot": [
      33,
      0
     ],
     "type": "sway"
    },
    "w": 66,
    "x": 52,
    "y": 30
   },
   {
    "file": "royalpalace_curtain1.png",
    "h": 270,
    "motion": {
     "amount": -0.01,
     "period": 7,
     "pivot": [
      38,
      0
     ],
     "type": "sway"
    },
    "w": 76,
    "x": 522,
    "y": 30
   },
   {
    "file": "royalpalace_chandelier0.png",
    "h": 21,
    "motion": {
     "max": 1.0,
     "min": 0.55,
     "speed": 2.5,
     "type": "flicker"
    },
    "w": 43,
    "x": 179,
    "y": 56
   },
   {
    "file": "royalpalace_chandelier1.png",
    "h": 21,
    "motion": {
     "max": 1.0,
     "min": 0.55,
     "speed": 3.5,
     "type": "flicker"
    },
    "w": 43,
    "x": 419,
    "y": 56
   }
  ]
 },
 "slantedsands": {
  "layers": [
   {
    "file": "slantedsands_sunglow.png",
    "h": 73,
    "motion": {
     "max": 1.0,
     "min": 0.6,
     "period": 6,
     "type": "pulse"
    },
    "w": 77,
    "x": 392,
    "y": 84
   },
   {
    "file": "slantedsands_clouds.png",
    "h": 137,
    "motion": {
     "speed": 4,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 62
   },
   {
    "file": "slantedsands_sand_far.png",
    "h": 61,
    "motion": {
     "speed": 9,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 282
   },
   {
    "file": "slantedsands_sand_near.png",
    "h": 55,
    "motion": {
     "speed": 18,
     "type": "drift"
    },
    "w": 640,
    "x": 0,
    "y": 344
   },
   {
    "file": "slantedsands_palm0.png",
    "h": 77,
    "motion": {
     "amount": 0.035,
     "period": 3.6,
     "phase": 0.0,
     "pivot": [
      1,
      76
     ],
     "type": "sway"
    },
    "w": 54,
    "x": 49,
    "y": 309
   },
   {
    "file": "slantedsands_palm1.png",
    "h": 73,
    "motion": {
     "amount": 0.035,
     "period": 4.05,
     "phase": 1.3,
     "pivot": [
      52,
      72
     ],
     "type": "sway"
    },
    "w": 54,
    "x": 554,
    "y": 318
   },
   {
    "file": "slantedsands_palm2.png",
    "h": 53,
    "motion": {
     "amount": 0.035,
     "period": 4.5,
     "phase": 2.6,
     "pivot": [
      42,
      52
     ],
     "type": "sway"
    },
    "w": 51,
    "x": 538,
    "y": 346
   }
  ]
 },
 "trainingcamp": {
  "effects": [
   {
    "amp": [
     2,
     5
    ],
    "cell": 16,
    "rect": [
     0.12,
     0.2,
     0.34,
     0.64
    ],
    "speed": [
     0,
     40
    ],
    "type": "ripple"
   },
   {
    "amp": [
     3,
     1
    ],
    "cell": 24,
    "rect": [
     0.1,
     0.62,
     0.62,
     0.74
    ],
    "speed": [
     10,
     0
    ],
    "type": "ripple"
   },
   {
    "amp": [
     6,
     1
    ],
    "cell": 70,
    "rect": [
     0,
     0.76,
     1,
     1
    ],
    "speed": [
     18,
     0
    ],
    "type": "ripple"
   },
   {
    "amp": [
     3,
     2
    ],
    "cell": 60,
    "rect": [
     0,
     0,
     0.47,
     0.42
    ],
    "speed": [
     7,
     2
    ],
    "type": "ripple"
   },
   {
    "amp": [
     3,
     2
    ],
    "cell": 60,
    "rect": [
     0.86,
     0.18,
     1,
     0.48
    ],
    "speed": [
     7,
     2
    ],
    "type": "ripple"
   }
  ]
 }
};
