// One theme per story world, in journey order, plus Custom. Each world's
// board, pieces, background and song share its id. `short` labels the small
// theme chips (Custom music/backdrop pickers).
const THEMES = [
  {
    id: 'pawnhollow',
    name: 'Pawn Hollow',
    short: 'Hollow',
    desc: 'A sleepy farm village of hay and orchards',
    colors: {
      lightSquare: '#d8b47a',
      darkSquare: '#6a9440',
      lightPiece: '#fff6e0',
      darkPiece: '#4a2e1a',
      highlight: '#ffd23f',
      legalMove: 'rgba(255,210,63,0.32)',
      background: '#14100a',
      panel: '#2a2014',
      text: '#fbecc8',
      accent: '#f2a53a',
      buttonBg: '#4a3620',
      buttonHover: '#5e4628',
      checkHighlight: '#ff4a3a',
    },
  },
  {
    id: 'trainingcamp',
    name: 'The Training Camp',
    short: 'Camp',
    desc: 'A dojo of tatami, dummies and holograms',
    colors: {
      lightSquare: '#d4c68c',
      darkSquare: '#7a5234',
      lightPiece: '#f4fbff',
      darkPiece: '#2a1c2e',
      highlight: '#6fe3ff',
      legalMove: 'rgba(111,227,255,0.3)',
      background: '#100c16',
      panel: '#1e1826',
      text: '#eee6ff',
      accent: '#6fe3ff',
      buttonBg: '#2e2440',
      buttonHover: '#3e3256',
      checkHighlight: '#ff3a6a',
    },
  },
  {
    id: 'slantedsands',
    name: 'The Slanted Sands',
    short: 'Sands',
    desc: 'Leaning pyramids on a tilted desert',
    colors: {
      lightSquare: '#e8c68c',
      darkSquare: '#b07640',
      lightPiece: '#fffbe6',
      darkPiece: '#3a2410',
      highlight: '#ff7a2a',
      legalMove: 'rgba(255,122,42,0.3)',
      background: '#1a0f06',
      panel: '#2c1a0c',
      text: '#f8e4b4',
      accent: '#ff7a2a',
      buttonBg: '#6a4218',
      buttonHover: '#845422',
      checkHighlight: '#ff2222',
    },
  },
  {
    id: 'ironkeep',
    name: 'The Iron Keep',
    short: 'Keep',
    desc: 'Riveted walls and a glowing forge',
    colors: {
      lightSquare: '#8e969f',
      darkSquare: '#4a5058',
      lightPiece: '#f2efe8',
      darkPiece: '#1e1a18',
      highlight: '#ff7a2a',
      legalMove: 'rgba(255,122,42,0.3)',
      background: '#0c0c10',
      panel: '#1a1c22',
      text: '#e4e8ee',
      accent: '#ff7a2a',
      buttonBg: '#2e323a',
      buttonHover: '#3e434d',
      checkHighlight: '#ff3322',
    },
  },
  {
    id: 'mistymoors',
    name: 'The Misty Moors',
    short: 'Moors',
    desc: 'Fog, heather and ruined watchtowers',
    colors: {
      lightSquare: '#8e9a84',
      darkSquare: '#4a5846',
      lightPiece: '#eef4ee',
      darkPiece: '#1c2420',
      highlight: '#9ff0d0',
      legalMove: 'rgba(159,240,208,0.28)',
      background: '#0a0f10',
      panel: '#151d1e',
      text: '#d6e4dc',
      accent: '#9ff0d0',
      buttonBg: '#243230',
      buttonHover: '#304240',
      checkHighlight: '#ff4a5a',
    },
  },
  {
    id: 'royalpalace',
    name: 'The Royal Palace',
    short: 'Palace',
    desc: 'Marble halls inlaid with gold',
    colors: {
      lightSquare: '#efe8e0',
      darkSquare: '#9a6272',
      lightPiece: '#fffaf0',
      darkPiece: '#3a1428',
      highlight: '#ffcf40',
      legalMove: 'rgba(255,207,64,0.3)',
      background: '#140a12',
      panel: '#24121e',
      text: '#fbeaf0',
      accent: '#ffcf40',
      buttonBg: '#4a2238',
      buttonHover: '#5e2e48',
      checkHighlight: '#ff2a5a',
    },
  },
  {
    id: 'clockworkcitadel',
    name: 'The Clockwork Citadel',
    short: 'Citadel',
    desc: 'Brass towers of ticking gears',
    colors: {
      lightSquare: '#d8b062',
      darkSquare: '#865826',
      lightPiece: '#fff4d8',
      darkPiece: '#241a14',
      highlight: '#4ae0d0',
      legalMove: 'rgba(74,224,208,0.28)',
      background: '#100a05',
      panel: '#1e140a',
      text: '#f2dcae',
      accent: '#4ae0d0',
      buttonBg: '#4a3218',
      buttonHover: '#5e4020',
      checkHighlight: '#ff4422',
    },
  },
  {
    id: 'grandlibrary',
    name: 'The Grand Library',
    short: 'Library',
    desc: 'Endless shelves by candlelight',
    colors: {
      lightSquare: '#c8985e',
      darkSquare: '#5a3420',
      lightPiece: '#fff6e4',
      darkPiece: '#2a1428',
      highlight: '#8ab8ff',
      legalMove: 'rgba(138,184,255,0.3)',
      background: '#0e0a0a',
      panel: '#1e1412',
      text: '#f4e2c4',
      accent: '#ffc860',
      buttonBg: '#3e2618',
      buttonHover: '#523222',
      checkHighlight: '#ff3a3a',
    },
  },
  {
    id: 'forkedgulch',
    name: 'Forked Gulch',
    short: 'Gulch',
    desc: 'Cacti, mesas and rolling tumbleweeds',
    colors: {
      lightSquare: '#d2ae84',
      darkSquare: '#80583a',
      lightPiece: '#faf0e6',
      darkPiece: '#3e2723',
      highlight: '#e8402a',
      legalMove: 'rgba(232,64,42,0.3)',
      background: '#1a1008',
      panel: '#2c1810',
      text: '#f0d6b0',
      accent: '#e8402a',
      buttonBg: '#5d4037',
      buttonHover: '#6d4c41',
      checkHighlight: '#ff2222',
    },
  },
  {
    id: 'obsidiancourt',
    name: 'The Obsidian Court',
    short: 'Court',
    desc: 'A black glass throne room over lava',
    colors: {
      lightSquare: '#7a7088',
      darkSquare: '#2a2432',
      lightPiece: '#f0e8e4',
      darkPiece: '#140e12',
      highlight: '#ff6a20',
      legalMove: 'rgba(255,106,32,0.3)',
      background: '#08060a',
      panel: '#161218',
      text: '#eee2dc',
      accent: '#ff6a20',
      buttonBg: '#2a2230',
      buttonHover: '#3a2e42',
      checkHighlight: '#ff2a2a',
    },
  },
  {
    id: 'crystal',
    name: 'Soulbound Pixel',
    short: 'Soulbound',
    desc: 'Crystal shards and glowing ether',
    colors: {
      lightSquare: '#e8dfcf',
      darkSquare: '#2b0d36',
      lightPiece: '#f4f0e8',
      darkPiece: '#1c1428',
      highlight: '#00e5ff',
      legalMove: 'rgba(0,229,255,0.28)',
      background: '#050508',
      panel: '#100b17',
      text: '#f4f0e8',
      accent: '#d932ff',
      buttonBg: '#1b1127',
      buttonHover: '#2b0d36',
      checkHighlight: '#ff2d8b',
    },
  },
  {
    id: 'custom',
    name: 'Custom',
    short: 'Custom',
    desc: 'Your own colors',
    colors: {
      lightSquare: '#8b9dc3',
      darkSquare: '#3b5998',
      lightPiece: '#ffffff',
      darkPiece: '#1a1a2e',
      highlight: '#e74c3c',
      legalMove: 'rgba(231,76,60,0.3)',
      background: '#0f0f1a',
      panel: '#1a1a2e',
      text: '#dfe3ee',
      accent: '#e74c3c',
      buttonBg: '#2a2a4e',
      buttonHover: '#3a3a6e',
      checkHighlight: '#ff4444',
    },
  },
];

// Themes from before the story worlds, and the world each became (the world
// that used it as placeholder art and took over its song).
const THEME_ALIASES = {
  japanese: 'pawnhollow',
  cyberpunk: 'trainingcamp',
  egypt: 'slantedsands',
  medieval: 'ironkeep',
  ocean: 'mistymoors',
  artdeco: 'royalpalace',
  steampunk: 'clockworkcitadel',
  space: 'grandlibrary',
  wildwest: 'forkedgulch',
  prehistoric: 'obsidiancourt',
};
